apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      protocol: TCP
  clusterIP: None
  selector:
    app: mongodb
