apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: exam
  labels:
    app: mongodb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.0.4
          ports:
            - containerPort: 27017
          volumeMounts:
              - name: data
                mountPath: /data
                readOnly: false
      volumes:
         - name: data
           persistentVolumeClaim:
             claimName: pvc-claim
